# Generated by Django 3.2.13 on 2022-06-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('protected657', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedfile',
            name='file_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='site',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='sites.site',
            ),
        ),
    ]
